### ISSUE TITLE
`omp_num_threads` is set after the first segment

### ISSUE THREAD

**Issue by gituser768** [terrierteam/pyterrier_ance#11]
I noticed that during indexing my processing time goes up significantly after the first segment has been indexed. Looking at the code I see `faiss.omp_set_num_threads(16)` after the first segment has been encoded (after the first call to `StreamInferenceDoc`). Pulling up `htop` I see that only 16 cores are in fact being utilized. My understanding is that setting the number of OMP threads is a global change, not something that is local to the FAISS index, so the encoding step is also being affected by this.

Is this intentional (meaning, is there a reason to set the number of threads to 16 rather than some other number, and why is it only set after the first segment is encoded)? 

If not, I can open a PR to take in the number of threads as an argument (although I would probably expect the calling code to handle setting the number of threads. If this was my project, I would remove the line entirely (as I seen you've done on the retrieval side (it is commented out))).

Thanks!

**Comment by cmacdonald** [comment]
Hi. good question.
this line comes from upstream, in ANCE: https://github.com/microsoft/ANCE/blob/master/drivers/run_ann_data_gen.py#L269

I would be amenable to removing it, assuming there is a reasonable default > 1. Faiss just exports the OpenMP call, and its not clear from the OpenMP call what the default is.

BTW, we're working on a new PyTerrier plugin framework for dense retrieval, which will be released in due course.

Craig

**Comment by gituser768** [comment]
Thanks for the quick response. I think in some implementations the default is 1, but I always find this stuff tricky since any package you use could override the value being used (at least that's my understanding).

Cool to know that there is a new plugin framework coming. What's the motivation for it? More specifically, do you expect to have support for "callbacks" type interface (or similar) so that the calling code can make modifications like this without having to modify code upstream?

If so, I might holdoff on these changes and just make them in my own fork of the library (to reduce work on your end).

**Comment by cmacdonald** [comment]
Working in your own fork is fine. This repo is clearly tied very much to the ANCE code released by Microsoft. But also happy to take PRs of things you think are useful for others.
