### ISSUE TITLE
Using ANCE Indexer for indexing new dataset

### ISSUE THREAD

**Issue by Watheq9** [terrierteam/pyterrier_ance#12]
I am wondering if there is a way to use ANCEIndexer to index my own dataset to enable applying dense retrieval? My dataset does not exist in your Dataset API.
@cmacdonald @seanmacavaney  @tonellotto  @Xiao0728

**Comment by seanmacavaney** [comment]
Hi @Watheq9,

All you need to do is pass an iterable of dicts that have the keys "docno" and "text". So for instance,

```python
documents = [
  {'docno': '1', 'text': 'hello terrier'},
  {'docno': '2', 'text': 'some document text'},
]
indexer.index(documents)
```

Depending on how large your corpus is, you may not want to load it all into memory at once. In that case, using a generator will work, e.g.,

```python
def doc_gen():
    with open('source_file') as f:
        for line in f:
            yield {'docno': ..., 'text': ...} # reading from the file as needed
indexer.index(doc_gen())
```

Does this help?

**Comment by Watheq9** [comment]
Hi @seanmacavaney ,
Thanks for your reply!
Yes, it worked. Then, ANCEIndexer and ColBERTIndexer classes can be used similar to the usage of IterDictIndexer, right?

**Comment by cmacdonald** [comment]
Correct. Its a standard pattern.
