### ISSUE TITLE
Hard coding `args`

### ISSUE THREAD

**Issue by gituser768** [terrierteam/pyterrier_ance#9]
Why is the `args` parameter local to the `index` method of `ANCEIndexer` instead of being defined as an attribute of the class instance? This makes it difficult to modify the arguments passed to the ANCE module (I would have to subclass the indexer class and implement a new `index` method which is identical to the one defined here, but with the `args` I want to pass).

`args` is defined on the class instance for `ANCERetrieval` so it probably makes sense to do the same for `ANCEIndexer`.

If you agree I'll open up a PR with this change.

**Comment by cmacdonald** [comment]
yes, good idea. Happy to accept a PR on this.
